#!/bin/sh
#
# Configured as part of the systemongrid 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF

#############

Welcome to SystemOnGrid

#############
-------------------------------------------------------------------------------
Welcome to the Django environment !


 postgresql default username and password : django:slieldjelso

Here we have install latest stable version of django 1.11 , pip , vitualenv, postgresql 9.5 with all dependencies

$ cd myproject 
$ . env/bin/activate
$ cd myproject 
$ ./manage.py makemigrations 
$ ./manage.py migrate
$ vim myproject/settings.py
 - Modify "ALLOWED_HOSTS" to contain the website address or an asterisk in quotes
$ ./manage.py runserver 0.0.0.0:8000


You can then view the sample app at http://${myip}:8000


-------------------------------------------------------------------------------
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF

