magento:
  image: vimagick/magento
  ports:
    - "80:80"
  links:
    - mysql
  restart: always

mysql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=magento
    - MYSQL_ROOT_HOST=172.17.0.3
  restart: always
