version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: K6wZnzkJ4GcQDjqt

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: K6wZnzkJ4GcQDjqt