#!/bin/sh
#
# Configured as part of the systemongrid 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF

#############

Welcome to SystemOnGrid

#############
-------------------------------------------------------------------------------
Redis environment

Here we have install Redis server  version $(redis-server --version)
Redis cli version $(redis-cli --version)




-------------------------------------------------------------------------------
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF

